name: Build and Deploy Project
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name : Set up MYSQL
      uses : mirromutth/mysql-action@v1.1
      with :
        mysql database: 'dbacpfinal' # Optional, default value is "test". The specified database which will be create
        mysql root password: ${{ secrets.MYSQL_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'root' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.MYSQL_PASSWORD }} #
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: 74112/acp14-final-project:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
      - name: Login to SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull 74112/acp14-final-project; \
            docker rm -f acp14-final-project; \
            touch myenv
            echo 'DBUSERNAME=${{ secrets.RDS_USERNAME }}'
            docker run -d --network host --name acp14-final-project 74112/acp14-final-project